/*** *** *** *** *** *** *** PEDIDO STATEMENTS *** *** *** *** *** *** ***/
/*** INSERT CABECERA STATEMENT ***/
INSERT INTO /*natom_*/cpbcab
(tipocpb,
numcpb,
codsuc,
codneg,
fechacpb,
usrgen,
usrmod,
fechagen,
fechamod,
tiposuj,
nrosuj,
ordendir,
nrovend,
nrocobr,
facturable,
tipocond,
condvta,
valorizado,
codmon,
cotizacion,
nrolistpre,
afectastock,
nrodep,
nrotransp,
nroentrega,
ordcompra,
nrosolicitud,
impbruto,
bonpie1p,
bonpie1i,
bonpie2p,
bonpie2i,
subtotal,
gravado,
exento,
impiva1,
impiva2,
perciva,
perciib,
percgan,
imptotal,
subtotalep,
gravadoep,
exentoep,
impiva1ep,
impiva2ep,
percivaep,
perciibep,
percganep,
imptotalep,
cantbult,
tipobult,
observac,
estado,
cerrado,
nrocierre,
contabil,
nroejerc,
nroasiento,
maqgen,
maqmod,
fiscal,
origcpb,
fechavto,
facturado,
impreso,
plazoentrega,
validezoferta,
desccont1p,
codmotivo,
nrosolcli,
recotizado,
observacint,
valordeclarado,
imprimebonif,
exportado,
numcpbaux,
canthojas,
nrocai,
venccai,
tipooper,
fechacaja,
fechaiva,
revisado,
formavta,
nroprov,
cotizaciondol,
nrolpr,
nrocanalventa,
fechaanticuacion,
direntrega,
descfin,
desccom,
excluirest,
nrocentrocli,
seguimiento,
fechaentrega,
codpcia,
recargo,
prioridad,
codiva,
nrotemporada,
codpostalent,
ordendirent,
ley16774,
creditoelectronica)
VALUES
('NPE',
/**[[-COMPROBANTE_NUMERO_SIN_GUIONES-]]**/,
1,
1,
'/**[[-COMPROBANTE_FECHA-]]**/',
118,	/* usergen */ /* Usuario (no activo) "CLIENTE DESDE ECOMMERCE" */
118,	/* usermod */ /* Usuario (no activo) "CLIENTE DESDE ECOMMERCE" */
NOW(),
NOW(),
'C',
/**[[-PK_CLIENTE_ID-]]**/,
1,
/**[[-CLIENTE_RESPONSABLE_ID-]]**/,	/* nrovend */
1,		/* nrocobr - SE ARRASTRA DEL ECOMMERCE VIEJO ESTE VALOR */
0,
'T',
/**[[-CLIENTE_COND_VTA_ID-]]**/,	/* condvta */
1,
'PES',
1,
/**[[-LISTA_PRECIO_ID-]]**/, /*nrolistaprec */
0,
1,
/**[[-NRO_TRANSP-]]**/,	/* TRANSPORTE PROPIO */ /* nrotransp */
1,
'',
/**[[-MONTO_TOTAL_NETO-]]**/,	/* subtotal */
/**[[-MONTO_TOTAL_NETO-]]**/,	/* impbruto */
0,
0,
0,
0,
/**[[-MONTO_TOTAL_NETO-]]**/,	/* subtotal */
/**[[-MONTO_TOTAL_GRAVADO-]]**/,  /* gravado */
/**[[-MONTO_TOTAL_EXENTO-]]**/,	/* exento */
/**[[-MONTO_TOTAL_IVA-]]**/, /* impiva1 */
0, /* impiva2 */
0,
1, /* perciibb */
0,
/**[[-MONTO_TOTAL_BRUTO-]]**/ + /**[[-MONTO_TOTAL_IIBB-]]**/,	/* imptotal */
/**[[-MONTO_TOTAL_NETO-]]**/,	/* subtotalep */
/**[[-MONTO_TOTAL_GRAVADO-]]**/, /* gravadoep */
/**[[-MONTO_TOTAL_EXENTO-]]**/,	/* exentoep */
/**[[-MONTO_TOTAL_IVA-]]**/, /* impivaep1 */
0, /* impivaep2 */
0,
/**[[-MONTO_TOTAL_IIBB-]]**/, /* perciibbep */
0,
/**[[-MONTO_TOTAL_BRUTO-]]**/ + /**[[-MONTO_TOTAL_IIBB-]]**/,	/* imptotalep */
0,
'',
'Pedido Web - /**[[-OBSERVACIONES_PEDIDO-]]**/',
'N',
0,
000000,
NULL,
0,
0,
'Carrito Web',
NULL,
0,
'E',
NOW(),
0,
0,
0,
0,
0,
0,
0,
0,
'Pedido ECOMMERCE',
0,	/* valordeclarado */
0,
0,
0,
0,
0,
NOW(),
'',
NOW(),
NOW(),
0,
0,
0,
1,
0,
177,	/* nrocanalventa */
NOW(),
'/**[[-DIRECCION_ENTREGA-]]**/',
0,
0,
0,
NULL,
NULL,
NOW(),
NULL,
0,
0,
0,
0,
0,
0,
0,
0);



/***QUERY_SPLIT***/
/*** INSERT DETALLE STATEMENT ***/
INSERT INTO /*natom_*/cpbdet
(tipocpb,
numcpb,
codsuc,
nrolinea,
nroart,
descrmod,
cantidad,
cantpend,
costoun,
precioun,
bonlinea1p,
importe,
nroaliciva,
bonlinea2p,
origcpb,
ctacompras,
nrosuj,
plazoentrega,
bonlinea3p,
bonlinea4p,
tiposuj,
nroprec,
observac,
numcpbaux,
numdespacho,
bonifci,
upc,
recarg1,
recarg2,
recarg3,
recarg4,
recargi,
unidades)
VALUES
('NPE',
/**[[-COMPROBANTE_NUMERO_SIN_GUIONES-]]**/,
1,
/**[[-NRO_LINEA-]]**/,
/**[[-ARTICULO_ID-]]**/,
NULL,
/**[[-CANTIDAD-]]**/ * /**[[-ARTICULO_UNIDMIN-]]**/, /*cantidad*/
/**[[-CANTIDAD-]]**/ * /**[[-ARTICULO_UNIDMIN-]]**/, /*cantpend*/
/**[[-ARTICULO_COSTO_UN-]]**/,	/* costoun */
/**[[-PRECIO_UNITARIO_NETO-]]**/ / /**[[-ARTICULO_UNIDMIN-]]**/, /*precioun*/
0,
/**[[-PRECIO_TOTAL_NETO-]]**/, /*importe*/
/**[[-ARTICULO_NROALICIVA-]]**/,
0,
'E',
NULL,
/**[[-PK_CLIENTE_ID-]]**/,
0,
0,
0,
'C',
/**[[-PK_CLIENTE_ID-]]**/,
NULL,
0,
NULL,
0,
0,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL);


/***QUERY_SPLIT***/
/*** *** *** *** *** *** *** STOCK STATEMENTS *** *** *** *** *** *** ***/
/*** INSERT INTO MOVSTOCK STATEMENT ***/
INSERT INTO /*natom_*/movstock
(
codsuc,
codneg,
nroart,
tipomov,
codmovstk,
fecha,
cantidad,
nrodep,
tipocpb,
numcpb,
usrgen,
catmov,
nrosuj,
origcpb,
tiposuj,
observac,
numcpbaux,
costotot,
codmon,
cotizacion)
VALUES
(
99,
10,
/**[[-ARTICULO_ID-]]**/,
'B',	/* BAJA */
2,		/* BAJA POR VENTA */
NOW(),
/**[[-CANTIDAD-]]**/,
1,		/* FARMACIA */
'NPE',
'/**[[-NUM_PEDIDO-]]**/',
9998,   /* USUARIO FANTASMA NATOM */
'V',	/* VENTA */
0,
'',
'',
'VENTA ONLINE eCommerce',
0,
0,
0,
1);

/***QUERY_SPLIT***/
/*** UPDATE ARTICULO STATEMENT ***/
UPDATE /*natom_*/articulos SET stockact = stockact - /**[[-CANT_PEDIDO-]]**/ WHERE nroart = /**[[-ARTICULO_ID-]]**/;